// Generated by scripts/generate-map-geometry.mjs. Do not edit by hand.
export const generatedDaNangRoute = {
  "id": "da-nang-highlights-prototype",
  "name": "Hành trình Đà Nẵng",
  "region": "Đà Nẵng",
  "geoPoints": [
    [
      108.2475,
      15.993
    ],
    [
      108.265725,
      16.005329
    ],
    [
      108.253,
      16.02
    ],
    [
      108.238,
      16.041
    ],
    [
      108.223197,
      16.060289
    ],
    [
      108.229958,
      16.061047
    ],
    [
      108.239,
      16.071
    ],
    [
      108.251,
      16.082
    ],
    [
      108.277559,
      16.099683
    ],
    [
      108.273,
      16.109
    ],
    [
      108.269,
      16.118
    ]
  ],
  "points": [
    {
      "x": 218.12,
      "y": 363.42
    },
    {
      "x": 218.66,
      "y": 363.04
    },
    {
      "x": 218.29,
      "y": 362.59
    },
    {
      "x": 217.84,
      "y": 361.94
    },
    {
      "x": 217.4,
      "y": 361.34
    },
    {
      "x": 217.6,
      "y": 361.32
    },
    {
      "x": 217.87,
      "y": 361.01
    },
    {
      "x": 218.23,
      "y": 360.67
    },
    {
      "x": 219.02,
      "y": 360.12
    },
    {
      "x": 218.88,
      "y": 359.83
    },
    {
      "x": 218.76,
      "y": 359.56
    }
  ],
  "stops": [
    {
      "id": "marble-mountains",
      "name": "Ngũ Hành Sơn",
      "coordinates": [
        108.265725,
        16.005329
      ],
      "pointIndex": 1,
      "label": {
        "x": 256.66,
        "y": 411.04,
        "anchor": "start"
      }
    },
    {
      "id": "museum-of-cham-sculpture",
      "name": "Bảo tàng Điêu khắc Chăm",
      "coordinates": [
        108.223197,
        16.060289
      ],
      "pointIndex": 4,
      "label": {
        "x": 175.4,
        "y": 392.34,
        "anchor": "end"
      }
    },
    {
      "id": "dragon-bridge-da-nang",
      "name": "Cầu Rồng",
      "coordinates": [
        108.229958,
        16.061047
      ],
      "pointIndex": 5,
      "label": {
        "x": 175.6,
        "y": 353.32,
        "anchor": "end"
      }
    },
    {
      "id": "linh-ung-pagoda-son-tra",
      "name": "Chùa Linh Ứng Sơn Trà",
      "coordinates": [
        108.277559,
        16.099683
      ],
      "pointIndex": 8,
      "label": {
        "x": 257.02,
        "y": 348.12,
        "anchor": "start"
      }
    },
    {
      "id": "son-tra-peninsula",
      "name": "Bán đảo Sơn Trà",
      "coordinates": [
        108.269,
        16.118
      ],
      "pointIndex": 10,
      "label": {
        "x": 258.76,
        "y": 381.56,
        "anchor": "start"
      }
    }
  ]
} as const;
